// This file was autogenerated by the build system, do not edit

#ifndef FLOW_VERSION_H_
#define FLOW_VERSION_H_

namespace Version {
    const char *const last_commit_date = "DATE_REPLACEME";
    const char *const last_commit_sha1 = "SHA1_REPLACEME";
}

#endif
