// This file was autogenerated by the build system, do not edit

#ifndef FLOW_VERSION_H_
#define FLOW_VERSION_H_

namespace Version {
    const char *const last_commit_date = "DATE_REPLACEME";
    const char *const last_commit_sha1 = "SHA1_REPLACEME";
    const char *const current_branch   = "BRANCH_REPLACEME";
    const bool isTag                   = ISTAG_REPLACEME; // If HEAD is a tag
    const bool hasGit                  = HASGIT_REPLACEME; // If .git is present
}

#endif
