// This file was autogenerated by the build system, do not edit

#ifndef FLOW_VERSION_H_
#define FLOW_VERSION_H_

namespace Version {
    const char *const last_commit_date = "2014-11-30";
    const char *const last_commit_sha1 = "010d4280dd22b9d53a843fcb89982a433d5cfde8";
    const char *const current_branch   = "master";
    const bool isTag                   = false; // If HEAD is a tag
    const bool hasGit                  = true; // If .git is present
}

#endif
