######################################################################
# Automatically generated by qmake (3.0) Sat Aug 9 21:57:32 2014
######################################################################

TEMPLATE = app
TARGET = qwebdavlib
INCLUDEPATH += . $$[QT_INSTALL_HEADERS]/QtNetwork $$[QT_INSTALL_HEADERS] $$[QT_INSTALL_HEADERS]/QtCore

# Input
SOURCES += main.cpp
LIBS += -lqwebdav

message($$INCLUDEPATH)
